[font]
size = 14
normal = { family = "whois", style = "Regular" }

# Colors (Greyscale)
# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#000000'
cursor = '#ffffff'

#Normal colors
[colors.normal]
black   = '#333333'
red     = '#444444'
green   = '#777777'
yellow  = '#999999'
blue    = '#aaaaaa'
magenta = '#cccccc'
cyan    = '#eeeeee'
white   = '#ffffff'

# Bright colors
[colors.bright]
black   = '#333333'
red     = '#444444'
green   = '#777777'
yellow  = '#999999'
blue    = '#aaaaaa'
magenta = '#cccccc'
cyan    = '#eeeeee'
white   = '#ffffff'
