# Colors (Green)
[window]
opacity = 1

[font]
size = 14
normal = { family = "Fixedsys62", style = "Regular" } 
#normal = { family = "VT323", style = "Regular" } 

# Default colors
[colors.primary]
background = '#000000'
foreground = '#0caf05'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#000000'
cursor = '#00ff00'

# Normal colors
[colors.normal]
black   = '#001E00'
red     = '#003400'
green   = '#00ff00'
yellow  = '#00FF4F'
blue    = '#00B14F'
magenta = '#008800'
cyan    = '#00EC64'
white   = '#00FF39'

# Bright colors
[colors.bright]
black   = '#001E00'
red     = '#003400'
green   = '#00ff00'
yellow  = '#00FF4F'
blue    = '#00B14F'
magenta = '#008800'
cyan    = '#00EC64'
white   = '#00FF39'
