[colors.primary]
background = "#15141b"
foreground = "#edecee"

[colors.cursor]
cursor = "#a277ff"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#110f18"
red = "#fb28a6"
green = "#40e0d0"
yellow = "#ffca85"
blue = "#4c4cff"
magenta = "#4c4cff"
cyan = "#40e0d0"
white = "#edecee"

[colors.bright]
black = "#4d4d4d"
red = "#fb28a6"
green = "#40e0d0"
yellow = "#ffca85"
blue = "#4c4cff"
magenta = "#4c4cff"
cyan = "#40e0d0"
white = "#edecee"
