# Colors (Green)
[window]
opacity = 1

[font]
size = 14
normal = { family = "Fixedsys62", style = "Regular" } 
#normal = { family = "VT323", style = "Regular" } 

# Default colors
[colors.primary]
background = '#000000'
foreground = '#00ff00'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#000000'
cursor = '#00ff00'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#00ff00'
green   = '#00ff00'
yellow  = '#00ff00'
blue    = '#00ff00'
magenta = '#00ff00'
cyan    = '#00ff00'
white   = '#00ff00'

# Bright colors
[colors.bright]
black   = '#000000'
red     = '#00ff00'
green   = '#00ff00'
yellow  = '#00ff00'
blue    = '#00ff00'
magenta = '#00ff00'
cyan    = '#00ff00'
white   = '#00ff00'
