# Colors (Somebody is Dead)
[window]
opacity = 0.75
# Default colors
[colors.primary]
background = '#000000'
foreground = '#dddddd'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#ab0000'
cursor = '#ff0000'

# Normal colors
[colors.normal]
black   = '#090909'
red     = '#801011'
green   = '#d00611'
yellow  = '#ff504f'
blue    = '#9190a1'
magenta = '#515051'
cyan    = '#fb0907'
white   = '#cccdc6'

# Bright colors
[colors.bright]
black   = '#808080'
red     = '#b04140'
green   = '#cf2f31'
yellow  = '#fe8081'
blue    = '#a0a0b0'
magenta = '#808080'
cyan    = '#fe2e2f'
white   = '#fefffe'
