# Cyber Punk Neon
# Source https//github.com/Roboron3042/Cyberpunk-Neon

[window]
opacity = 0.95

[font]
size = 12
normal = { family = "VCR OSD Mono", style = "Regular" }

# Default colors
[colors.primary]
background = '#040030'
foreground = '#0077ff'

[colors.cursor]
text   = '#0077ff'
cursor = '#ff00ff'

# Normal colors
[colors.normal]
black   = '#123e7c'
red     = '#ff0000'
green   = '#d300c4'
yellow  = '#f57800'
blue    = '#123e7c'
magenta = '#711c91'
cyan    = '#0abdc6'
white   = '#d7d7d5'

# Bright colors
[colors.bright]
black   = '#1c61c2'
red     = '#ff0000'
green   = '#d300c4'
yellow  = '#f57800'
blue    = '#00ff00'
magenta = '#711c91'
cyan    = '#0abdc6'
white   = '#d7d7d5'
